nginx-proxy/nginx-proxy

- nginx.tmpl
As per RFC4329, nginx uses application/javascript as the default MIME
type for .js files. Nginx-proxy will now gzip these files if the client
requests it.
> Gzip application/javascript

- Dockerfile
Nginx complains when some containers export very long `VIRTUAL_HOST` (in my case 50 character long).
This error is painful because either:
- nginx is already running when I start the container with long name: then nginx will silently keep using the old configuration and my new container and any container added after that won't be load-balanced.
- the long name containers are running before nginx-proxy is started, then nginx-proxy will fail to start and no container will be load-balanced at all.
My workaround was to shorten the host name by setting `VIRTUAL_HOST=just-the-host-name.*`.
As better fix, this PR increases the nginx `server_names_hash_bucket_size` parameter to 128 (it was already increased from 32 to 64 in #9).
> Allow for even longer virtual host names (should work to at least 50 chars).

- nginx.tmpl
nginx was throwing the following error: `no "ssl_certificate" is defined in server listening on SSL port while SSL handshaking`
fixes: https://github.com/jwilder/nginx-proxy/issues/74
the idea is to only create the 443 server if there is a default certificate available.
> fixes SSL support while mixing HTTPS and non-HTTPS hosts

- README.md
- nginx.tmpl
This PR adds the ability to configuration Nginx settings on a per `VIRTUAL_HOST` basis by adding a configuration file under `/etc/nginx/vhost.d`. As in the case of SSL configuration and basic authentication, the files in this directory are expected to be named after the `VIRTUAL_HOST` value verbatim (without `.conf`).
I also added some documentation around providing custom Nginx configuration on a proxy-wide basis. The whole README.md is starting to feel pretty messy to me, so it may make sense at some point to do an editing pass on it as a whole or to move large parts of it into wiki pages.
Fixes #29, #36, #39, #70, #76, #87 
Related #71
> Per VIRTUAL_HOST configuration files

- nginx.tmpl
Uses Nginx's $host instead of interpolating `{{ $host }}` in the template
Refs #92
> Fix HTTP->HTTPS redirect for wildcard hosts

- nginx.tmpl
includeSubdomains can lead to issues where not all subdomains are
able to use HTTPS.  This options might be too strict for the general
case: https://www.owasp.org/index.php/HTTP_Strict_Transport_Security.
It can be re-enabled w/ a custom template if needed.
Fixes #109
> Remove includeSubdomains from HSTS header

- Dockerfile
The latest `nginx` image is 1.7.10, so here's an update.
I'd probably be inclined to set this to `nginx:1.7` myself and set up a repository link on Docker Hub to trigger an automated build whenever `nginx:1.7` is updated, but I understand there are drawbacks to that approach.
> Update to nginx:1.7.10

- nginx.tmpl
If a client is not providing the Upgrade HTTP header with the request, the connection will now be marked as 'to close' when finished.
See [#46](https://github.com/jwilder/nginx-proxy/pull/46) for more info.
Added a .gitignore by accident or out of habit as well.
> Close marker instead of empty

- Dockerfile
- README.md
- nginx.tmpl
When launching nginx-proxy you can use an env var to set which should be the default host header. If an env var is not defined then the default 503 will be returned. 
Closes #25
> Ability to set a default host for nginx

- README.md
As it is written, the "Separate Containers" section of the README doesn't work.  I added the jwilder repository to the docker-gen image name, assuming that the user won't have a local build named docker-gen, and also changed the docker-gen behavior from -only-published to -only-exposed, to match the nginx-proxy container's behavior.
> Fix a couple things in the README.

- README.md
- nginx.tmpl
Added detection for DH group by site in the format ```<hostname>.dhparam.pem```, if file exists then use it.
* [The Logjam Attack](https://weakdh.org/)
* [Guide to Deploying Diffie-Hellman for TLS](https://weakdh.org/sysadmin.html)
* [CVE-2015-1716](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-1716)
> Add support for ssl_dhparam to prevent 'Logjam' attack

- README.md
Changes to README.md to encourage use of a read-only mount for /var/run/docker.sock
Closes #173
> Encourage using read-only mount for docker.sock

- nginx.tmpl
This PR completes support for Swarm cluster.
This will also pick up any containers running on a remote host that is in the Swarm cluster and uses the host address/port instead of container address/port.
> Use container host's IP:port if we're connected to a swarm master

- README.md
Both boot2docker and docker-machine will work fine with the normal `docker run`
command used in the rest of the docs.
> Remove boot2docker-specific instructions

- Dockerfile
- docker-entrypoint.sh
This PR implements a safeguard feature that will make the nginx-proxy container refuse to start if the `/tmp/docker.sock` socket isn't available _(or whatever unix socket file path given with `DOCKER_HOST`)_.
The intent is to reduce the number of support requests received such as #234 
When the docker socket isn't available, the container displays an explicit error message with a link to the _usage_ section of the README file.
Those changes where made following the [Docker Official Images](https://github.com/docker-library/official-images/blob/master/README.md) guidelines. And as such it adds a new behaviour to the image:
- when **no parameter** is passed to the container → **usual behavior**
- when **parameter `forego start -r`** is passed to the container → **usual behavior**
- …
> refuse to start if the docker sock isn't available

- nginx.tmpl
This resolves the issue where accessing a non-existent hostname over HTTPS returns the first SSL-enabled virtual host instead of correctly responding with a 503 error.
> Fix for #188 - remove hostname from default SSL block

- Makefile
- circle.yml
- test/lib/docker_helpers.bash
Since CircleCI now [supports docker 1.9.1](https://discuss.circleci.com/t/docker-1-9-1-is-available/1009)
> CircleCI: make tests run on Docker 1.9.1

- Dockerfile
- Makefile
- test/default-host.bats
- test/docker.bats
- test/lib/docker_helpers.bash
- test/multiple-hosts.bats
- test/multiple-ports.bats
- test/test_helpers.bash
- test/wildcard-hosts.bats
Since [`jwilder/docker-gen@5043565`][1] some timings seem to have changed. This caused the unit tests to fail intermittently, from my testings especially on Ubuntu systems (much less often on e.g. Arch).
This commit adds the `dockergen_wait_for_event` helper-function to try and wait for the configuration to be generated by docker-gen before continuing on with the actual tests themselves.
Additionally, at the end of every test file, all containers spun up by the bats-tests will be stopped. This required adding the `bats-type` label to every container started during the bats-tests.
The stopping of the containers reduces the amount of events docker-gen has to process, thus resulting in lower wait times for the generation to happen.
[1]: …
> Update to docker-gen 0.7.0

- Dockerfile
- Makefile
- README.md
- circle.yml
- nginx.tmpl
- test/docker.bats
- test/lib/docker_helpers.bash
- Migrate docker-gen from 0.4.2 to 0.5.0 (add []Network supports)
- Nginx template use now current IP into network.
- Documentation updated. Proxy must run it with the option --net=host to access at all differents networks (overlay network support - tested with ```docker-compose --x-networking up -d```)
> Support Overlay Network

- README.md
- nginx.tmpl
- test/ssl.bats
First, thanks to @palamccc for reporting this in #453.
When using `HTTP_METHOD=noredirect`, the user is essentially saying "don't automatically redirect my users from HTTP to HTTPS, however, users that end up at the HTTPS site are still being sent the HSTS header, which forces the client to redirect all HTTP requests to HTTPS.  My feeling is that HSTS should be removed when `HTTPS_METHOD=noredirect`.
I have implemented the change in this PR and added tests to cover the normal HSTS behavior and the `noredirect` behavior (after sifting through the bats docs for an hour before stumbling on `refute_output` :) ).
I've also expanded the documentation on `HTTPS_METHOD` as suggested in #446
> Disable HSTS when HTTPS_METHOD=noredirect

- nginx.tmpl
Updating a variable inside an `if` does update the outer scoped variable.
> Revert 9c93efa

- README.md
- nginx.tmpl
The so-called `httpoxy` attack [see httpoxy.org, CVE-2016-(5385-5388,1000109-1000110)] occurs when an errant client sends an HTTP `Proxy` request header.  This is non-standard, and no well-behaved client will send this header.  Many languages (PHP, Python, Golang), when used in a CGI scenario expose this header as an environment variable `HTTP_PROXY` in the CGI environment (as per the CGI spec).  Unfortunately, many server-side HTTP clients use that environment variable as the address of an outbound HTTP proxy, meaning an attacker can easily coerce a backend server to send private, internal HTTP traffic out to the public internet, to a destination of their choice.
This PR tells Nginx to suppress that header, and not forward it on to the backend servers.
> Mitigate httpoxy attack by suppressing `Proxy` request header

- nginx.tmpl
Before commit e95d3e9fdf7e8959b989f5868f555345274ad563 HSTS was only enabled for those FQDN that where managed by nginx-proxy - it did not bother the operation of any other subdomain. 
As the HSTS setting now includes subdomains a user is forced to provide all existing subdomains via HTTPS which might be not intended (i.e. https://domain.tld is serviced by nginx-proxy, non-related http://some.service.domain.tld is now forced to use HTTPS).
The PR reverts the behaviour to the former default.
It might be worth considering to introduce a ENV setting to _optionally_ enable `includeSubDomains`?
> do not enable HSTS for subdomains

- nginx.tmpl
I have a domain key-mydomain.com. When I add domain www.key-mydomain.com with ssl cert I did not get the desired result. Function replace cut name ssl cert "www.key-mydomain.com.key" to "www-mydomain.com".
> Replace "replace" to "trimSuffix"

- README.md
- nginx.tmpl
- test/docker.bats
- test/headers.bats
- test/multiple-hosts.bats
- test/multiple-ports.bats
- test/test_helpers.bash
- test/web_helpers/webserver.py
This PR adds the `X-Forwarded-Port` HTTP request header.  Just as `X-Forwarded-Proto` reflects the protocol that was used to connect to the proxy (`http` or `https`), this header reflects the port that was used to connect to the proxy (`80`, `443`, `8080`, etc).  This is important because without it there is no way for a downstream application to know what port was used by the client to connect, and therefore, it is impossible to rebuild the original hostname / URL.  Like `X-Forwarded-Proto`, if a request is received by `nginx-proxy` with an already-defined `X-Forwarded-Port`, that value is passed unaltered, but if it is not present, the header is generated.  This allows it to operate behind another instance of `nginx-proxy` or other servers that use this defacto standard, like the AWS …
> Added X-Forwarded-Port and proxy headers tests

- .travis.yml
This PR upgrades `docker-engine` in Travis-CI from `1.12.1` to `1.12.3` and adds the `--allow-downgrades` flag.  Without this flag, when `1.12.4` comes out, `apt-get` will fail with an error because it does not allow automated downgrades of packages without confirmation, so all builds will start to fail (this just happened in #590 ).
> Travis-CI - upgrade docker-engine and allow downgrades

- Dockerfile.alpine
- Makefile
Hi,
this PR adds a new alpine linux based version. 
Background: Nginx alpine ships with a newer openssl version and supports ALPN.
```
bash-4.3# nginx -V
nginx version: nginx/1.11.3
built by gcc 5.3.0 (Alpine 5.3.0)
built with OpenSSL 1.0.2h  3 May 2016
TLS SNI support enabled
```
I think it's better to keep the current nginx-proxy with debian and provide a second variant.
Try it: https://hub.docker.com/r/matthh/nginx-proxy/tags/
I simply created another automated build with "/Dockerfile.alpine" for "Dockerfile Location".
BTW: Different file sizes are amazing...
TODO:
- Create a new automated build with "alpine-latest" tag
- Add info to README
> Add alpine base image

- nginx.tmpl
- test/wildcard-hosts.bats
This PR adds tests to show a case where the nginx configuration file produced is not valid and makes nginx fail to reload.
----
`$ bats wildcard-hosts.bats`
✓ [wildcard-hosts] start a nginx-proxy container
✓ [wildcard-hosts] VIRTUAL_HOST=*.wildcard.bats
✓ [wildcard-hosts] VIRTUAL_HOST=wildcard.bats.*
✓ [wildcard-hosts] VIRTUAL_HOST=~^foo\.bar\..*\.bats
✗ [wildcard-hosts] VIRTUAL_HOST=~^foo\.bar\..*\.bats$
(from function `assert_output' in file lib/bats/batslib.bash, line 328,
from function `assert_200' in file wildcard-hosts.bats, line 83,
in test file wildcard-hosts.bats, line 65)
`assert_200 foo.bar.whatever.bats' failed
HTTP/1.1 503 Service Temporarily Unavailable
ab2531a8a276
container_name: bats-wildcard-hosts-4
ports: 80
options: -e VIRTUAL_HOST=~^foo.bar..*.bats$
expose_option: …
> fix crash when using end-of-string symbol `$` in regex VIRTUAL_HOST

- README.md
- nginx.tmpl
Many projects look for X-Forwarded-Ssl header, so it can simplify things for some users.
On the other hand I can see no downside in merging this.
> Set appropriate X-Forwarded-Ssl header

- README.md
- nginx.tmpl
- test/ssl.bats
This feature complements `HTTPS_METHOD=nohttp`, which disables the HTTP site.  For containers with `HTTPS_METHOD=nohttps` set, the template sets `is_https` to `false`, which treats everything as if there was no matching certificate.  
This solves issue #573, in which a user needs to disable the HTTPS site for a specific container with a subdomain that happens to match the SSL cert of another container.
A test has also been added to cover this directive.
> Added HTTPS_METHOD=nohttps to disable SSL site

- Procfile
This tiny change will prevent most of the recent issues I encountered using this image. 
To reproduce:
1) add ssl keys to proper directory
2) start a container A with VIRTUAL_HOST
3) nginx-proxy will create default.conf configuration properly
4) remove the ssl keys from directory
5) restart nginx proxy to refresh the configuration
6) nginx will be stuck in "restart" loop because it can't find the removed SSL key, which is in its configuration, since the first thing this image does is starting nginx instead of recreating configuration
This change will first generate configuration, then start the nginx, so it will update the default.conf to use it without ssl keys properly
To reproduce:
1) start nginx_proxy normally
2) add a container A with VIRTUAL_HOST and "net" which nginx_proxy is not a …
> First load docker-gen, then nginx

- nginx.tmpl
Change a bit the new way to name upstream introduced in #671. With this PR, the new way to name upstreams is only triggered if matching hostname with a regular expression. 
The intent is to reduce changes to existing users who might have added custom conf to the vhost.d directory as discovered in #677
> regexp: use sha1 for upstream only if regexp is used

- README.md
PR #344 changed the HTTP status code from `503` to `500`. The README.md file was not updated accordingly.
> DOC: reflect change from PR #344

- README.md
- nginx.tmpl
Demo
~~~
version: '2'
services:
nginx-proxy:
image: qiqizjl/nginx-proxy
container_name: nginx-proxy
ports:
- "81:80"
volumes:
- /var/run/docker.sock:/tmp/docker.sock:ro
php-fpm:
image: php:fpm-alpine
environment:
- VIRTUAL_HOST=php-fpm.local
- VIRTUAL_ROOT=/var/www/html
- VIRTUAL_PORT=9000
- VIRTUAL_PROTO=fastcgi
~~~
> support fastcgi

- Dockerfile
- README.md
- network_internal.conf
- nginx.tmpl
After using `nginx-proxy` for a year or two, I've bumped into this scenario several times:
I have a `nginx-proxy` container running on a server, and use port-forwarding to send traffic from the public internet to that container.  I run many containers on that same server, but some of them are only for internal network usage (a local intranet site, etc).  Currently, external clients could access these internal sites from the public internet if they just forge the `Host` header (for example, by editing their `hosts` file).
This PR adds an environment variable `NETWORK_ACCESS`, which can be set to `external` (default) or `internal`.  If `internal` is used, the file `/etc/nginx/network_internal.conf` is included in each `server` block with the following contents:
```
allow 127.0.0.0/8;
allow …
```
> Allow containers to be restricted to internal network

- README.md
- nginx.tmpl
The existence of `/etc/nginx/dhparam/dhparam.pem` should be tested and not presumed, as the separate container setup described in the doc won't auto generate this file (neither `docker-gen` nor `nginx` has this capability), and SSL can work without it.
Presuming the file is here leads to failure when one attempt to use SSL on the separate container setup with self provided certificate (ie without using an automated solution like the recommended [JrCs/docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion) or when using self signed default cert).
This issue has been described by @returntrip there : https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/264#issuecomment-338893690
> Fix default dhparam.pem when using separate containers

- README.md
- nginx.tmpl
- test/test_ssl/test_hsts.py
- test/test_ssl/test_hsts.yml
This PR adds custom HSTS support as discussed in #953.
It's available from my Docker repo as `kamermans/nginx-proxy:feature_custom_hsts`.
Note that the tests are passing, but there are two other tests failing on my build machine.  At least one of them is due to a change in output in `openssl 1.1.0` on my Ubuntu 17.10 test machine, so I'll probably send a PR for that issue later.
> Added custom HSTS support (issue #953)

- test/test_ssl/test_dhparam.py
- test/test_ssl/wildcard_cert_and_nohttps/test_wildcard_cert_nohttps.py
The following tests are failing on my build machine (Ubuntu 17.10):
1. `test_ssl/test_dhparam.py::test_web5_dhparam_is_used` - was failing because the `openssl s_client` was used with `-verify 0` to disable certificate verification.  `-verify 0` has actually been wrong forever, but only recently has `openssl` stopped tolerating it.  Removing the `-verify` statement entirely disables certificate verification properly.
2. `test_ssl/wildcard_cert_and_nohttps/test_wildcard_cert_nohttps.py::test_web3_https_is_500_and_SSL_validation_fails` - was failing because `requests` raises a `SSLError(CertificateError)`, but we're expecting the inner error, a `CertificateError`.  I don't know if this is related to my version of Python (`2.7.14`) or `requests` (`2.18.4)`, but on my machine I get an …
> Fixed failing SSL tests

- nginx.tmpl
Sometimes containers will not be assigned an IP (after reboot or due to misconfiguration). This leads to an incorrect `server <missing ip here> down;` line in default.conf and crashes nginx. 
@therealgambo provided a fix for this: #845
> Fallback if container has no IP

- nginx.tmpl
The nginx.tmpl was looking for the chain certificate with the file extension of .crt when in fact the chain certificate has a .pem extension. Adjusted the template to ensure SSL stapling was correctly enabled by detecting the correct file.
> OCSP Stapling was not working

- README.md
In PR #984, no instructions were added to the README that told the user how to enable OCSP Stapling.  This PR adds those instructions.
> Added docs on enabling OCSP Stapling

- .travis.yml
- test/conftest.py
- test/requirements/python-requirements.txt
I don't know why this only seems to fail in Docker `18.04 RC3`, but I can confirm that it consistently fails in that version and not in older versions.  This actually fixes two bugs:
1. In `docker-compose 1.11.1`, the code pulls some internal code from `pip`, but `pip` removed that code and so `docker-compose` broke.  This was fixed in `docker-compose 1.11.2`, so I've upgraded that, and had to upgrade `docker-py` as well, to meet the minimum requirements.
2. In one of our tests, we were opening a file handle via `with` and reading from it after the `with` was closed, so the variable was out of scope.  Fixed with a single indent.
@jwilder This PR will fix the failing builds in PRs #1123, #1083, #1116, #1120.
> Bugfix: Test reads from out-of-scope var

- nginx.tmpl
- test/test_ssl/test_hsts.py
- test/test_ssl/test_hsts.yml
This fixes issue #1080.  It was caused by a typo in the logic which made it impossible to disable HSTS if `HTTPS_METHOD=noredirect`.  Complex logical comparison in this templating language (go's `text/template`) is really confusing!
> Fixed #1080, can't disable HSTS with noredirect

- generate-dhparam.sh
When launch the container, the default dhparam.pem is cleared to 0 by shell redirection while creating a new dhparam.pem.
```
root@0841481db300:/app# cd /etc/nginx/dhparam/
root@0841481db300:/etc/nginx/dhparam# ls -lha
total 0
drwxr-xr-x 1 root root 25 Dec 16 13:40 .
drwxr-xr-x 1 root root 35 Dec 16 12:18 ..
-rw-r--r-- 1 root root  0 Dec 16 13:40 dhparam.pem
```
So, nginx sometimes fails to initialize.
```
WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
forego     | starting dockergen.1 on port 5000
forego     | starting nginx.1 on port 5100
dockergen.1 | 2018/12/16 13:40:02 Generated '/etc/nginx/conf.d/default.conf' …
```
> Fix empty dhparam.pem

- README.md
- docker-entrypoint.sh
- generate-dhparam.sh
With the integration of [letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion). When both containers start at the same time, sometimes both containers are trying to generate Dh-Param at the same time which could be heavily taxing thus, adding an option to disable the generation of dh param and only let `letsencrypt-nginx-proxy-companion` do the generating, or offers an already generated dh param.
> Add DH param generator option

- nginx.tmpl
> fix fastcgi bug

- nginx.tmpl
The auto renewal of Let'sEncrypt certificates fails due to the HTTPS redirect of the ACME challenge.
This workaround resolves the issue:
https://gist.github.com/codekitchen/2c519eb7572002afab6a5f979cd42913#file-letsencrypt-diff
Found through this comment:
https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/526#issuecomment-476253642
> Do not HTTPS redirect Let'sEncrypt ACME challenge

- Dockerfile
- Dockerfile.alpine
- README.md
This PR upgrades Nginx to version 1.17.8, see [CHANGES](https://nginx.org/en/CHANGES) for more information.
> Upgrade to 1.17.8

- nginx.tmpl
This PR allows to choose arbitrary ports for HTTP and HTTPS instead of 80 and 443.
While it does not change anything in the way ports can be mapped to host using native Docker capabilities, it fixes the "invalid" `X-Forwarded-Port` when the port on which nginx listens to is different from the one it is mapped - and accessed by clients - on the host.
Typical usage in docker-compose (here with the custom ports `1080` and `10443`):
```
reverse-proxy:
image: jwilder/nginx-proxy
ports:
- "1080:1080"
- "10443:10443"
environment:
HTTP_PORT: "1080"
HTTPS_PORT: "10443"
volumes:
- /var/run/docker.sock:/tmp/docker.sock:ro
```
I'm open to suggestions.
Thanks for your amazing work on this image, it helps a lot.
Regards,
> Add support for custom external HTTP/HTTPS ports

- nginx.tmpl
This PR removes the access_log lines from the generated nginx config if DISABLE_ACCESS_LOGS env var is set in the nginx-proxy container.
I think this would solve issue #503
> Set DISABLE_ACCESS_LOGS env var to disable access logs

- README.md
The Docker Hub links are stale. They take you to a page which loads the Docker Hub header and footer, but no content about the image.
The new URLs load the image description correctly.
> Fix docker-gen Docker Hub URL

- README.md
- nginx.tmpl
The current implementation requires each container to set the `HTTPS_METHOD` and `HSTS` environment variable individually. This pr adds an intermediate fallback to allow setting the value also on the main nginx-proxy container. If they are not set, the default will be the same as before.
> Add fallback to the proxy containers env for HTTPS_METHOD and HSTS

- nginx.tmpl
Add the following to the Let's Encrypt ACME challenge "no redirection to HTTPS"
https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/pull/570
https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/pull/335
> Bring ACME no redirection inline with companion

- Dockerfile
- Dockerfile.alpine
Previously, the Dockerfile downloaded 'docker-gen' and 'forego' binaries during build time. This caused a problem as it hard-coded the amd64 architecture for the images.
This PR updates both 'Dockerfile' and 'Dockerfile.alpine' to build the `forego` and `docker-gen` executables from source instead of downloading binaries directly. This is achieved using multi-stage builds [1]. Two separate stages first build the binaries, and are then copied over to the final stage.
The advantage of this change is two-fold: First, it enables building this image on architectures other than amd64. Second it adds trust by not adding external binaries to the docker image.
This modified version passes the tests both a linux desktop (`amd64`) as well as a raspberry pi (`armv7`) with some caveats:
- On `armv7`, …
> Enable multi-architecture docker image builds

- README.md
- docker-entrypoint.sh
Default key size is not 2048 anymore but 4096 bits, reference : https://github.com/nginx-proxy/nginx-proxy/blob/master/generate-dhparam.sh#L4
> Update docker-entrypoint.sh comment on DHPARAM default key size

- README.md
Example docker-compose.yml does not work without defining an exposed port for whoami service.
> Update README.md - sample yml needed expose option

- .github/ISSUE_TEMPLATE.md
The Google Forum no longer exists. Therefore the link to it in the issue template should be removed.
> Remove Google Forum Link from Issue Template

- Dockerfile
- Dockerfile.alpine
This PR updates **jwilder/docker-gen** to the latest tagged release, `0.7.6`, which should fixe a number of `no servers inside upstream in /etc/nginx/conf.d/default.conf` issues.
The Dockerfiles are now fetching docker-gen sources using `git` rather than downloading a tar archive. The fetching of the sources, building and cleanup are done in a single layer to minimize the size of the intermediate-stage image.
close #1548
close #1585
close #1586
close #1600
> Bump docker-gen from 0.7.4 to 0.7.6

- Dockerfile
- Dockerfile.alpine
> It's very common to have thousands of clients, especially for a public website. I stopped counting the amount of websites I've seen went down because of the low defaults.
[source](https://serverfault.com/questions/787919/optimal-value-for-nginx-worker-connections)
> Upd: Boost worker_connections from 1024 to 10240.

- nginx.tmpl
> Suffix upstream names to prevent confusion with FQDNs

- docker-entrypoint.sh
- generate-dhparam.sh
PR #913 added `DHPARAM_GENERATION` as a positional argument to generate-dhparam.sh. However, since it was the second positional argument,`DHPARAM_BITS` would also have to be defined or `DHPARAM_GENERATION` would be read into `DHPARAM_BITS`. This changes the arguments to be inherited variables which do not depend on order, just declaration.
Also change instances of `GENERATE_DHPARAM` to `DHPARAM_GENERATION` since it's unnecessary to have another variable. I think `GENERATE_DHPARAM` is actually a better name (verb vs. noun), but `DHPARAM_GENERATION` is already defined and may break someone if changed.
Addresses https://github.com/jwilder/nginx-proxy/pull/913#issuecomment-476014691
----
```
$ docker run -it --rm -e "DHPARAM_GENERATION=false" testing /bin/bash
WARNING: …
```
> Change dhparam positional args to be inherited vars, standardize naming

- nginx.tmpl
Hello! Thanks for awesome project!
I use nginx on same machine to terminate SSL and serve static files. So my nginx-proxy instances are http-only and use only docker network. That's why I got `X-Forwarded-Ssl` set always to "off" because it based on `$scheme`. In my PR I utilise `$proxy_x_forwarded_proto` mapping (which based on `X-Forwarded-Proto` header and falls back to `$scheme` if empty) to detect ssl connection.
> Set proper X-Forwarded-Ssl for SSL-terminated setups

- test/certs/create_server_certificate.sh
Docker image `nginx:1.14.1` has no `openssl` installed. Therefore upgrading to `nginx:1.19.10`.
**Before**:
```
$ test/certs/create_server_certificate.sh web.nginx-proxy.tld
Unable to find image 'nginx:1.14.1' locally
1.14.1: Pulling from library/nginx
a5a6f2f73cd8: Pulling fs layer
2343eb083a4e: Pulling fs layer
251439d5b33c: Pulling fs layer
251439d5b33c: Verifying Checksum
251439d5b33c: Download complete
a5a6f2f73cd8: Verifying Checksum
a5a6f2f73cd8: Download complete
2343eb083a4e: Verifying Checksum
2343eb083a4e: Download complete
a5a6f2f73cd8: Pull complete
2343eb083a4e: Pull complete
251439d5b33c: Pull complete
Digest: sha256:32fdf92b4e986e109e4db0865758020cb0c3b70d6ba80d02fe87bad5cc3dc228
Status: Downloaded newer image for nginx:1.14.1
> Create a host key: …
```
> Fix broken create_server_certificate.sh

- README.md
- nginx.tmpl
- test/test_debug/test_proxy-debug-flag.py
- test/test_debug/test_proxy-debug-flag.yml
- test/test_debug/test_server-debug-flag.py
- test/test_debug/test_server-debug-flag.yml
- test/test_multiple-ports/test_VIRTUAL_PORT-single-different-from-single-port.py
- test/test_multiple-ports/test_VIRTUAL_PORT-single-different-from-single-port.yml
The VIRTUAL_PORT environment variable should always be honored.
Even when the related port is not exposed.
Fix for #1132.
This commit also add the DEBUG environment variable which enables more
verbose comments in the nginx comfiguration file to help troubleshooting
unreachable containers.
Finaly it fixes #1105 as well by defining only one
fallback entry per upstream block.
> Honor VIRTUAL_PORT + DEBUG flag + fallback entry

- nginx.tmpl
Currently its almost impossible to know which host actually handled the request, this extra variable logs the upstream server too
> Improve logging

- README.md
- nginx.tmpl
- test/test_http_port.py
- test/test_http_port.yml
- test/test_ssl/test_https_port.py
- test/test_ssl/test_https_port.yml
This PR adds docs and tests for #1353  plus fix and tests for HTTPS redirection when using custom HTTPS port.
The fix and the tests are adapted from those of @stuckj in #1234
> Docs and tests for custom HTTP/HTTPS ports

- nginx.tmpl
- test/test_debug/test_proxy-debug-flag.py
- test/test_server-down/test_no-server-down.py
- test/test_server-down/test_no-server-down.yml
- test/test_server-down/test_server-down.py
- test/test_server-down/test_server-down.yml
See https://github.com/nginx-proxy/nginx-proxy/pull/1609#issuecomment-858150285.
Additionally, fix a warning due to a missing backslash escaping from previous merge request.
> Use `server 127.0.0.1 down` entry only when required

- README.md
- nginx.tmpl
- test/test_events.py
- test/test_virtual-path/test_virtual_paths.py
- test/test_virtual-path/test_virtual_paths.yml
This is a work in progress combination of #599 + #1011 + #1083 + #1594 with proper authoring credits.
- `VIRTUAL_PATH`: route using this path
- `VIRTUAL_DEST`: rewrite the query path (optional)
- Support for custom config snippets files
- Add test cases
NOTE: This requires another pull request to function  jwilder/docker-gen#343 to function.
> Support for path-based routing

- Dockerfile
- Dockerfile.alpine
This PR updates **docker-gen** to release `0.7.7`.
This might fix some lingering issues where docker-gen can't find its own container ID in some OSes and Docker versions, which in turn leads to configurations where all `upstream` contains only `server 127.0.0.1 down;` (see https://github.com/nginx-proxy/docker-gen/issues/355)
> Bump docker-gen from 0.7.6 to 0.7.7

- nginx.tmpl
- test/test_raw-ip-vhost.py
- test/test_raw-ip-vhost.yml
This PR adds tests for raw IPv4/IPv6 `VIRTUAL_HOST` and fixes #1693 by using sha1 hashes of the hostname as `upstream` names (which was already the case for regexp `VIRTUAL_HOST`) rather than suffixing the hostname with `-upstream`.
> Use sha1 of hostname as upstream names

- README.md
- nginx.tmpl
- test/test_upstream-name/test_predictable-name.py
- test/test_upstream-name/test_predictable-name.yml
- test/test_upstream-name/test_sha1-name.py
- test/test_upstream-name/test_sha1-name.yml
I decided to backpedal and revert both #1163 and #1725 so that people that relied on predictable `upstream` blocks names won't have their setup break on them.
As an alternative fix to #1162, I added an optional `SHA1_UPSTREAM_NAME` environment variable to nginx-proxy which, when set to `true`, will forces the `upstream` block's names to SHA1 hashes of the hostnames in the same manner as #1725 did.
@cheald I believe this PR will solve your original issues without breaking stuff for others like the previous solution did.
@akpircher, @tkw1536, @acortelyou, @EricSoroos sorry for the back and forth on this one.
> Revert to predictable upstream names, optional SHA1 names

- test/conftest.py
There isn't really any need to check for an exact version of the Docker python module down to the patch release.
This will ease dependabot updates of the test dependencies.
> Ease version check on python docker module for tests

- .github/workflows/dockerhub.yml
Fixes #1769 
As discussed with @thaJeztah it might be an issue with the Git context through BuildKit (cc @tonistiigi).
Permissions in the working tree look correct:
```text
$ git ls-files -s .
100644 8fafbb04eb32b001b3a9dfd9f2a4a6d5b926f238 0       .dockerignore
100644 99d688b08ac835d24415631c0430478966d98a7b 0       .github/ISSUE_TEMPLATE.md
100644 9056ae137af1ca95e49e91af65718e050727adbd 0       .github/dependabot.yml
100644 5d4cfba4cababa6e10d8dab2fec8686f8f938e47 0       .github/workflows/dockerhub.yml
100644 6be93bd487f038e482b6c342671501b5589fc0fa 0       .github/workflows/test.yml
100644 5daab4f78ff8f34540bd8e64add0db0270426689 0       .gitignore
100644 97c0cc9acad1a057c95117013a4d9f5860a10bac 0       Dockerfile
100644 c08dcc3d560910c385657e360428c3da819dfbcb 0 …
```
> Use path context

- README.md
Since the second option got removed, the "either" makes no sense any more and may lead to confusion about non existent alternatives
> Clarify grammar in DH-GROUP section

- Dockerfile
- Dockerfile.alpine
- README.md
- test/stress_tests/test_deleted_cert/test_restart_while_missing_cert.py
Bumps nginx from 1.21.3 to 1.21.4., supersede #1821.
> Bump nginx to 1.21.4

- test/conftest.py
- test/pytest.sh
- test/requirements/Dockerfile-nginx-proxy-tester
This PR contributes [fixes I described here](https://github.com/nginx-proxy/nginx-proxy/pull/1848#issuecomment-1003247877) when investigating test failures from running pytest via the supported Docker container method (my preference).
I've scoped changes out to individual commits as usual, with commit messages adding context. The final commit does a little housekeeping with white-space so it might be a cleaner diff if you disable white-space when viewing.
---
Roughly the changes are:
- Proper detection of running `pytest` via container (`pytest.sh`) by using ENV instead of the deprecated internal file check that Docker no longer supports. We only need it for running tests and control the `pytest` Dockerfile, seems the right way to approach it :+1: 
- Supporting host networking mode …
> tests: Fix pytest container networking issues

- .github/workflows/dockerhub.yml
- Dockerfile
- Dockerfile.alpine
- Makefile
- docker-entrypoint.sh
- nginx.tmpl
- test/test_nominal.py
This PR adds a build argument and an associated environment variable to the Dockerfile whose intent are to store nginx-proxy's version. This environment variable is in turn used to display nginx-proxy's version at startup and on the generated nginx configuration.
The current version is retrieved and injected to the image built and pushed by the CI pretty much in the same way as in nginx-proxy/docker-gen and nginx-proxy/acme-companion.
> Add and display nginx-proxy version

- README.md
`/etc/nginx/conf.d/default.conf` is accidentally listed as `/etc/nginx/conf.d/default` a couple times in README.md
> Fix path to default.conf in README.md

- test/conftest.py
When running tests against the `nginxproxy/nginx-proxy:test` it can happen that someone uses an invalid configuration yaml file for spinning up containers. It then can happen that the proxy container exits immediately and the test logs don't provide any further information.
This PR adds the docker container logs output in case the  `nginxproxy/nginx-proxy:test` exited unexpectedly before tests are run. 
A sample output looks like this:
```
DEBUG    DNS:conftest.py:243 resolving domain name ('www.web2.nginx-proxy.tld', 80, <AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>)
DEBUG    DNS:conftest.py:190 nginx_proxy_dns_resolver('www.web2.nginx-proxy.tld')
WARNING  DNS:conftest.py:194 no container found from image nginxproxy/nginx-proxy:test while resolving 'www.web2.nginx-proxy.tld' …
```
> Add container logs in case testcontainer exited unexpectedly

- Dockerfile
- Dockerfile.alpine
This PR updates docker-gen to release `0.8.2`.
> Bump docker-gen to 0.8.2

- Dockerfile
- Dockerfile.alpine
docker-gen `0.9.0` add template functions from the [sprig library](https://masterminds.github.io/sprig/), (see https://github.com/nginx-proxy/docker-gen/pull/418) along with the new `{{break}}` and `{{continue}}` actions in [text/template](https://pkg.go.dev/text/template).
> Bump docker-gen from 0.8.4 to 0.9.0

- nginx.tmpl
- test/test_vhost-in-multiple-networks.py
- test/test_vhost-in-multiple-networks.yml
Whenever **docker-gen** catches a new event, it tries to generate a new **nginx.conf**, even when an event is unrelated to the proxied containers.
Since **DockerClient** does not guarantee the order in a `Container.Networks` list, each config re-generation may result in a different order of debug messages in the **upstream** section. 
For example, the first run will produce the following config:
```nginx
upstream web.example.com {
server 172.16.1.10:80;
}
```
While some other time the order will be different:
```nginx
upstream web.example.com {
server 172.16.1.10:80;
}
```
When there are hundreds of containers starting/stopping in a Docker, it leads to a lot of useless Nginx reloads.
> Make sure networks order is the same

- README.md
- nginx.tmpl
- test/test_headers/test_http.py
- test/test_headers/test_https.py
- test/test_trust-downstream-proxy/test_default.py
- test/test_trust-downstream-proxy/test_disabled.py
- test/test_trust-downstream-proxy/test_enabled.py
This is the same as PR #1836 except:
* Rebased onto latest `main` revision
* The header is now covered by the new  `TRUST_DOWNSTREAM_PROXY` setting (#1927)
* Added more documentation
* Added tests
* Added myself as a co-author
cc @xujif @SilverFire
> feat: Add proxy header `X-Forwarded-Host`

- nginx.tmpl
No behavior changes, just cleanups.
> Various code health chores

- README.md
- nginx.tmpl
- test/test_default-root-none.py
- test/test_default-root-none.yml
> feat: `DEFAULT_ROOT=none` disables the default `location /` block

- nginx.tmpl
- test/test_multiple-networks.py
- test/test_multiple-networks.yml
Multiple commits: several cleanups and a fix for a minor bug.
> fix: Generate at most one `server` directive per container

- Makefile
- test/pytest.sh
This is a no-op if the images are already up to date, and it prevents puzzling problems when the images are old.
> chore: Pass `--pull` to `docker build` to get fresh images

- README.md
- nginx.tmpl
- test/test_location-override.py
- test/test_location-override.vhost.d/explicit-nonroot.nginx-proxy.test_8d960560c82f4e6c8b1b0f03eb30a1afd00e5696_location_override
- test/test_location-override.vhost.d/explicit-root-hash-and-nohash.nginx-proxy.test_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
- test/test_location-override.vhost.d/explicit-root-hash-and-nohash.nginx-proxy.test_location_override
- test/test_location-override.vhost.d/explicit-root-hash.nginx-proxy.test_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
- test/test_location-override.vhost.d/explicit-root-nohash.nginx-proxy.test_location_override
- test/test_location-override.vhost.d/implicit-root-hash-and-nohash.nginx-proxy.test_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
- test/test_location-override.vhost.d/implicit-root-hash-and-nohash.nginx-proxy.test_location_override
- test/test_location-override.vhost.d/implicit-root-hash.nginx-proxy.test_42099b4af021e53fd8fd4e056c2568d7c2e3ffa8_location_override
- test/test_location-override.vhost.d/implicit-root-nohash.nginx-proxy.test_location_override
- test/test_location-override.yml
Under the existing implementation, it would be impossible to change the actual behavior of the default location block, which attempts to proxy_pass onto the container.  This is probably acceptable for many use cases but not all.
This change adds some additional template logic that considers the existence of a `VIRTUAL_HOST_locations` (plural "locations" as opposed to the otherwise considered "location") configuration file.  When present, it will bypass generating any nginx `location` blocks and instead use those provided by the configuration file.  
This allows for some really advanced use cases with nginx's location filtering.  You can then forward the root location of a monitored domain onto a completely different container or even an entirely external host while still introducing logic …
> Allow complete override of location blocks

- nginx.tmpl
It doesn't work with the newer Docker Swarm mode so it doesn't have much value anymore.
> chore: Remove support for legacy swarm

- nginx.tmpl
Please review and test, as I do not have any knowledge of the used template language
This should fix #2182 and the old issue of `docker-gen` (https://github.com/nginx-proxy/docker-gen/issues/431)
> fix: Sort networks and ports before iterating

- nginx.tmpl
This partially reverts commit 2494e207843c92a715da3e8e65ed763fd0d2d624 by ignoring any network named "ingress" when searching for a container's IP address.
That commit was technically a backwards-incompatible change: Some users use nginx-proxy with Swarm mode even though it is not fully supported.  In such cases nginx-proxy should ignore the `ingress` network, otherwise nginx will not be able to reach the server (container-to-container traffic apparently doesn't work over the Swarm `ingress` network).
The parts of that commit that examine the `SwarmNode` structure are not reverted here because docker-gen does not currently populate that structure—not even when both docker-gen and the service task container are running on the same manager node.
See discussion #2172
> fix: Partially revert "chore: Remove support for legacy swarm"

- test/conftest.py
- test/test_ssl/test_dhparam.py
These changes will make it easier to add tests for planned features.
> chore: Minor test improvements

- nginx.tmpl
Also:
* Note when there are no networks.
* Fix "networks available" comment.
Fixes #2189
> fix: Don't error if `$globals.CurrentContainer` is `nil`

- README.md
- nginx.tmpl
- test/test_keepalive.py
- test/test_keepalive.yml
Fixes #609
Note: This depends on PR #2127, and will be marked as draft until that PR is merged.
> feat: Add support for HTTP keep-alive between the proxy and upstream

- README.md
- nginx.tmpl
- test/test_loadbalancing.py
- test/test_loadbalancing.yml
Currently all connections are forwarded upstream with Round Robin algorithm. (default Nginx)
This pull request adds a container labels to specify the load balancing algorithm. Which can be used to have session persistence / affinity.
Some web applications which use the HTTP long-polling transport like websocket require sticky sessions.
Related #871, #299, #221, #886
Note if #1934 is merged: When using load balancing methods other than the default round-robin method, it is necessary to activate them before the keepalive directive.
If you think this PR is usefull I also plan to add the 'weight' directive.
I am trying to write a test. I have no pytest experience and having a little hard time to setup the test suite.
```
def test_web_loadbalance(docker_compose, nginxproxy):
conf = …
```
> feat: Add support for HTTP load balancing between the proxy and upstream server groups

- .github/dependabot.yml
This PR:
- add GitHub Actions ecosystem to Dependabot
- schedule test suite dependencies check weekly down from daily
> ci: maintain GitHub Actions with Dependabot

- .github/workflows/build-publish.yml
We're not publishing on DockerHub only, this PR reflects that.
> ci: rename build / publish workflow

- .github/workflows/build-publish.yml
- Dockerfile
- Dockerfile.alpine
This PR change the Dockerfiles to get the docker-gen binary from the `nginxproxy/docker-gen` image instead of building it, like acme-companion does.
The actual value of `DOCKER_GEN_VERSION` isn't important for acme-companion so we use a placeholder value in the Dockerfiles and let the CI provide the real value as build arg.
> build: get docker-gen from pre-built image

- Dockerfile
- Dockerfile.alpine
This was only used a (long) while ago to get docker-gen and/or forego binaries.
> build: don't install wget inside images

- nginx.tmpl
This PR should fix an issue with Secure Renegociation (RFC 5746) [identified](https://github.com/nginx-proxy/nginx-proxy/pull/2186#issuecomment-1533863923) by @SchoNie and introduced in #2186 
That's counterintuitive but it seems like the `ssl_session_cache` must be enabled as soon as there is an active fallback HTTPS listener if we want secure renegociation to work, even if we're going to return a TLS error from the fallback listener.
@SchoNie I tested the PR with both SSL Labs and OpenSSL and it appears to fix the issue, could you confirm ?
> fix: always on session cache on HTTPS fallback listener

- Dockerfile
- Dockerfile.alpine
Pretty much the same as #2230 but for forego, which now have a pre built image (`nginxproxy/forego`).
The [diff between version `0.17.0` and `0.17.1`](https://github.com/nginx-proxy/forego/compare/v0.17.0...v0.17.1) is pretty much just dependencies maintenance and the new Dockerfiles + GitHub Action workflow required for the images building and publishing.
I don't plan on doing any work on forego beside this and the occasional dependencies bump, so this PR aim is mostly to further simplify nginx-proxy Dockerfiles and get yet another small bump in build speed.
> build: get forego from pre-built image

- README.md
- docker-compose-separate-containers.yml
- docker-compose.yml
- test/conftest.py
- test/test_composev2.py
- test/test_composev2.yml
- test/test_custom/test_defaults-location.py
- test/test_custom/test_defaults-location.yml
- test/test_custom/test_defaults.py
- test/test_custom/test_defaults.yml
- test/test_custom/test_location-per-vhost.py
- test/test_custom/test_location-per-vhost.yml
- test/test_custom/test_per-vhost.py
- test/test_custom/test_per-vhost.yml
- test/test_custom/test_proxy-wide.py
- test/test_custom/test_proxy-wide.yml
- test/test_internal/test_internal-per-vhost.py
- test/test_internal/test_internal-per-vhost.yml
- test/test_internal/test_internal-per-vpath.py
- test/test_internal/test_internal-per-vpath.yml
- test/test_multiple-networks.py
- test/test_multiple-networks.yml
- test/test_vhost-in-multiple-networks.py
- test/test_vhost-in-multiple-networks.yml
Issue: https://github.com/nginx-proxy/nginx-proxy/issues/2249
.local domains are special use domains for mDNS and must not be used for other routing purposes,
use .internal instead in documentation.
See RFC 6762 for details: https://datatracker.ietf.org/doc/html/rfc6762
> fix: Replace mDNS .local domain with .internal domain

- README.md
- nginx.tmpl
- test/conftest.py
- test/test_host-network-mode/test_host-network-mode.py
- test/test_host-network-mode/test_host-network-mode.yml
- test/test_host-network-mode/test_proxy-host-network-mode.py
- test/test_host-network-mode/test_proxy-host-network-mode.yml
Containers which run host networking do not have their own IP address, which means the template doesn't know what to use as the upstream server. This change detects if a target container is running host networking, and if so, uses the IP address of the bridge net gateway as the upstream target.
Fixes #1270 
Fixes #832
> Support containers running --net=host (#1537)

- README.md
- nginx.tmpl
- test/test_http2/test_http2_global_disabled.py
- test/test_http2/test_http2_global_disabled.yml
- test/test_http3/test_http3_global_disabled.py
- test/test_http3/test_http3_global_disabled.yml
- test/test_http3/test_http3_global_enabled.py
- test/test_http3/test_http3_global_enabled.yml
- test/test_http3/test_http3_vhost.py
- test/test_http3/test_http3_vhost.yml
- test/test_ssl/test_hsts.py
- test/test_ssl/test_hsts.yml
@SchoNie I went the extra mile and opened a draft PR with what I got so far. It seems mostly functional to me, let me know if you think something is missing / should be done differently.
It indeed work when replacing `proxy_set_header Host $http_host;` with `proxy_set_header Host $host;`, should we also replace the other uses of `$http_host` beside this one ?
The PR still lacks documentation at this point, and I don't think it can be automatically tested beside parsing the rendered template (Python's `request` is not even capable of doing HTTP/2).
New labels on the **proxied** containers:
- `com.github.nginx-proxy.nginx-proxy.http2.enable`:
enable HTTP/2 support when set to `true` (default: `true`)
- `com.github.nginx-proxy.nginx-proxy.http3.enable`:
enable HTTP/3 support when set to …
> feat: experimental HTTP/3 support + optional HTTP/2 disabling

- test/README.md
- test/conftest.py
Enable overriding default 'docker compose' command with environment variable 'DOCKER_COMPOSE'. This way docker compose v1 is still supported with:
$ DOCKER_COMPOSE=docker-compose pytest
This is important because people using the Debian packaged docker compose are stuck to v1.
> Tests: support custom 'docker compose' command

- test/pytest.ini
- Pretty terminal output colors.
- Remove obsolete "-r s" which is there to hide "Skipped" tests from summary text. But seems to be of no use as there are no skipped tests.
> Pytest color terminal output

- test/stress_tests/test_deleted_cert/test_restart_while_missing_cert.py
Tests in `stress_tests\test_restart_while_missing_cert.py` were being marked as xfailed and some others are partial. But I do not see a special reason. (nor could find in the commit history).
So I removed the xfail and incremental markers. And fixed 2 tests.
Now CI should have 100% passed score.
If there was a reason they should be xfail / xpass where I was not aware off just delete this PR.
> Fix xpass and xfails test_restart_while_missing_cert.py

- Dockerfile.alpine
- Dockerfile.debian
- app/Procfile
This PR remove unneeded stuff from the Dockerfiles:
- rather than adding `daemon off;` to `/etc/nginx/nginx.conf`, start nginx with `-g "daemon off;"` on the procfile
- upstream `/etc/nginx/nginx.conf` already has `worker_processes auto;`, no need to edit the file for this
- upstream image already has up to date `ca-certificates`
- `openssl` is not a required dependency for either image
> refactor: cleanup dockerfiles

- test/README.md
- test/requirements/Dockerfile-nginx-proxy-tester
Follow up of #2343 to make sure Docker Compose v2 is installed in the `nginx-proxy-tester` image.
- Install docker-ce-cli and docker-compose-plugin from [official apt repository instructions](https://docs.docker.com/engine/install/debian/#install-using-the-repository) in the nginx-proxy-tester image.
- Document Docker Compose v2 requirement in tests readme
Just `docker-compose-plugin` or `docker-ce-cli` was not enough. Both seems to be required. 
I went for the the apt install method, so we do not have to track updates or dependencies.
> test: install docker compose in nginx-proxy-tester image

- Dockerfile.alpine
The OpenSSL CLI was removed from the alpine image in #2359 because it wasn't a required dependencies, but it was useful to some people (see #2371). Since it's a small size difference, let's add it back.
> build: add the openssl cli back to the alpine image

- docs/README.md
- nginx.tmpl
- test/test_keepalive.py
- test/test_keepalive.yml
This PR adds an `auto` setting to `com.github.nginx-proxy.nginx-proxy.keepalive` that dynamically set the maximum number of idle connections to twice the number of servers listed in the corresponding `upstream{}` block, [per nginx recommendation](https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#no-keepalives).
Given the fact that nginx lists not enabling keepalive connections to upstream as one of the top ten mistake, the `auto` setting will probably soon be made default (with the possibility to explicitly disable keepalive with `com.github.nginx-proxy.nginx-proxy.keepalive: "disabled"`).
> feat: keepalive auto setting

- Dockerfile.alpine
- Dockerfile.debian
This is an attempted fix for #1780 by setting [worker_rlimit_nofile](https://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile) value to two times the value we use for [worker_connections](https://nginx.org/en/docs/ngx_core_module.html#worker_connections) (10240 x 2 = 20480). [This is what is recommended by nginx as a minimum](https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#insufficient-fds) and it appeared to fix #1780 for @danifr
The hard to decipher regex is used to insert `worker_rlimit_nofile 20480;` to `/etc/nginx/nginx.conf` only once, after the first occurence of the character `}`.
> fix: set worker_rlimit_nofile to (worker_connections x 2)

- nginx.tmpl
This fix #2386 by emulating the behaviour we had before #2278, when the port number was included in the `Host` header for non standard ports.
See also https://github.com/nginx-proxy/nginx-proxy/discussions/2271#discussioncomment-6475824 and https://github.com/nginx-proxy/nginx-proxy/discussions/2271#discussioncomment-8156338
@EarthCompass I think this will fix the issue you had.
> fix: add non standard port to Host header

- docs/README.md
- nginx.tmpl
- test/test_log_json.py
- test/test_log_json.yml
- test/test_log_json_format.py
- test/test_log_json_format.yml
https://github.com/nginx-proxy/nginx-proxy/discussions/2133
Introduces 3 new environmental variables:
- `LOG_FORMAT`
- `LOG_FORMAT_ESCAPE`
- `LOG_JSON`
`LOG_FORMAT` and `LOG_FORMAT_ESCAPE` default to standard values. When `LOG_JSON` is set, defaults are changed to: `{"time_local":"$time_iso8601","client_ip":"$http_x_forwarded_for","remote_addr":"$remote_addr","request":"$request","status":"$status","body_bytes_sent":"$body_bytes_sent","request_time":"$request_time","upstream_response_time":"$upstream_response_time","upstream_addr":"$upstream_addr","http_referrer":"$http_referer","http_user_agent":"$http_user_agent","request_id":"$request_id"}`and `json`.
See `nginx.tmpl` and https://nginx.org/en/docs/http/ngx_http_log_module.html#log_format for details
> Add more control over log_format config directive

- test/test_http_port.py
- test/test_ssl/test_https_port.py
Tests for #2388: Make sure the port number is included in the Host header for non standard ports.
> tests: non standard port Host header check

- Dockerfile.alpine
- Dockerfile.debian
- README.md
- test/certs/create_server_certificate.sh
[nginx 1.25.4-alpine image seems to be inconsistently available for some archs](https://github.com/nginxinc/docker-nginx/issues/866), which result in CI build failure.
1.5.1 release will be removed until this is fixed.
> build: revert nginx to 1.25.3

- docs/README.md
- nginx.tmpl
- Small readability (code highlighting) adjustments in the htpassword docs part
- Fixed link to htpasswd Apache docs page
- Removed hardcoded `/` as `virtual_path` should already contain it
> docs: htpasswd readability

- nginx.tmpl
This PR refactors the template internals to facilitate #1504 
It centralise vhosts and vpaths values precomputation in a single `range` loop and remove some duplicated code.
<details>
<summary>The data structure stored for now in <code>$globals.vhosts</code> look like this :</summary>
```json
{
"foo.bar.com": {
"cert": "",
"cert_ok": false,
"default": false,
"hsts": "max-age=31536000",
"http2_enabled": true,
"http3_enabled": false,
"https_method": "redirect",
"paths": {
"/": {
"containers": [{}],
"dest": "",
"network_tag": "external",
"proto": "http",
"upstream": "foo.bar.com"
}
},
"server_tokens": "",
"ssl_policy": "",
"vhost_root": "/var/www/public"
},{
"multipath.bar.com": {
"cert": "",
"cert_ok": false,
"default": false,
"hsts": "max-age=31536000",
"http2_enabled": true, …
```
> refactor: template internal data structure

- test/requirements/web/webserver.py
> Changed in Python version 3.12: Unrecognized escape sequences produce a SyntaxWarning. In a future Python version they will be eventually a SyntaxError.
[2.4.1.1. Escape sequences](https://docs.python.org/3/reference/lexical_analysis.html#index-23)
Change to raw string literal to fix:
```
/webserver.py:17: SyntaxWarning: invalid escape sequence '\d'
elif re.match("/status/(\d+)", self.path):
/webserver.py:18: SyntaxWarning: invalid escape sequence '\d'
result = re.match("/status/(\d+)", self.path)
```
> fix: tests webserver syntaxwarning

- docs/README.md
Fix 404 to docker-entrypoint.sh
Add hyperlink to nginx.tmpl reference.
> docs: url fixes

- test/test_build.py
Tests for: [Dockerfile-nginx-proxy-tester](https://github.com/nginx-proxy/nginx-proxy/blob/main/test/requirements/Dockerfile-nginx-proxy-tester)
Test if we can build and run (and verify pytest output) the nginx-proxy-tester image. As the Dockerfile installs quite some dependencies and there is no place we currently check if it works.
If things break by future change we should see in CI.
> tests: add test if nginx-proxy-builder can be build successfully

- test/requirements/web/Dockerfile
- test/requirements/web/entrypoint.sh
This PR use the alpine variant of the python Docker image as a base for the `web` test helper image, as we don't need the significantly larger debian variant.
> test: use python alpine variant as base for web image

- test/test_build.py
Without this patch the test fails when run from project base directory.
> fix 'requirements' path in test/test_build.py

- nginx.tmpl
- test/test_fallback.py
- test/test_ssl/test_nohttp.py
Without this fix the response of nohttp sites to HTTP requests changes depending on the existence of at least one HTTP enabled site:
* no HTTP enabled sites -> connection refused
* at least one HTTP enabled site -> 503
This fix ensures the response is always 503.
> fix: constistent behavior for `HTTPS_METHOD=nohttp`

- nginx.tmpl
Rebase of #2011 by @rodrigoaguilera 
Should fix #1466
> fix: include a complete fastcgi_params config

- test/requirements/python-requirements.txt
requests version >= `2.32.0` is currently incompatible with docker-py `7.0.0`, see https://github.com/docker/docker-py/issues/3256 and https://github.com/psf/requests/issues/6707
This reverts commit 1c1f8e8700eaba62af96e63ef885b6efbe90f069.
> fix: hardcode requests package version to 2.31.0

- Dockerfile.alpine
- Dockerfile.debian
- docs/README.md
- nginx.tmpl
- test/test_custom-error-page/50x.html
- test/test_custom-error-page/test_custom-error-page.py
- test/test_custom-error-page/test_custom-error-page.yml
This PR restore the default error page provided by the nginx container and allows to customise it by mounting another HTML file in its place.
Solve #1325
> feat: custom default error page

- docs/README.md
- nginx.tmpl
This doesn't change the current nginx-proxy behavior, but makes explicit the current HTTPS_METHOD policy on missing certificate.
> chore/doc: explicit policy on missing certificate

- docs/README.md
- nginx.tmpl
- test/test_enable_http_on_missing_cert.py
- test/test_enable_http_on_missing_cert.yml
There is no reason to silently switch to noredirect on missing cert.
The default being `HTTPS_METHOD=redirect` most of the test cases need to set `HTTPS_METHOD=nohttps` or `HTTPS_METHOD=noredirect`.
> fix: enforce HTTPS_METHOD on missing cert as well

- nginx.tmpl
This should fix #2496 by using the correct file on Debian and Alpine.
@fauzanelka could you test the [`nginxproxy/nginx-proxy:2496`](https://hub.docker.com/layers/nginxproxy/nginx-proxy/2496/images/sha256-14feb8587e866aeea288047794606718fb131caa10a254626215323bbb1ee7ce?context=repo) image ?
> fix: use fastcgi.conf on alpine and fastcgi_params on debien

- nginx.tmpl
This fixes the problem described in [this issue](https://github.com/nginx-proxy/nginx-proxy/issues/2492) where containers that expose a large number of ports will cause the template to render a line exceeding the max line length of Nginx.
> Limit exposed ports in template to 10

- Dockerfile.alpine
- Dockerfile.debian
- README.md
- test/certs/create_server_certificate.sh
Normally Dependabot will trigger this but there is an issue: https://github.com/dependabot/dependabot-core/issues/10452 the nginx 1.27.1 image is being detected as pre-release.
I waited 2 weeks but there seems no progress in that issue so I decided to create this PR.
Changes with nginx 1.27.1                                        14 Aug 2024
*) Security: processing of a specially crafted mp4 file by the
ngx_http_mp4_module might cause a worker process crash
(CVE-2024-7347).
Thanks to Nils Bars.
*) Change: now the stream module handler is not mandatory.
*) Bugfix: new HTTP/2 connections might ignore graceful shutdown of old
worker processes.
Thanks to Kasei Wang.
*) Bugfixes in HTTP/3.
> build: bump nginx 1.27.0 to 1.27.1

- docs/README.md
- nginx.tmpl
- test/test_fallback.py
This PR fixes #2287
This might have worked at some point to reject SSL connections but clearly does not anymore ( you can't pass empty data to  `ssl_certificate` / `ssl_certificate_key`, as seen in #2287 ):
```nginx
ssl_ciphers aNULL;
set $empty "";
ssl_certificate data:$empty;
ssl_certificate_key data:$empty;
if ($https) {
return 444;
}
```
The correct way to do this is by using [`ssl_reject_handshake`](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_reject_handshake).
> fix: reject SSL handshake rather than using empty certificate

- docs/README.md
- nginx.tmpl
- test/test_debug_endpoint/test_global.py
- test/test_debug_endpoint/test_global.yml
- test/test_debug_endpoint/test_per_container.py
- test/test_debug_endpoint/test_per_container.yml
This PR add an optional (disabled by default) debug endpoint to virtual hosts, either activated globally or on a per virtual host basis.
It should help tests and issue solving by exposing meaningful internal config and data structure through externally available JSON rather than having to navigate through the generated config. I also hope that it might help sanitise the internal data structure itself.
The endpoint would be accessible through the `/nginx-proxy-debug` route when enabled.
```console
curl -ssk https://test.nginx-proxy.tld/nginx-proxy-debug | jq
```
<details>
```json
{
"global": {
"default_cert_ok": false,
"default_root_response": "404",
"enable_access_log": true,
"enable_debug_endpoint": "false",
"enable_ipv6": false,
"external_http_port": "80",
"external_https_port": "443", …
```
> feat: nginx-proxy debug endpoint

- docs/README.md
- nginx.tmpl
This PR create a corresponding entry in the `$globals.config` map for every `$globals.ENV.*` value that where previously accessed throughout the template, so those global values can be displayed by the debug endpoint from #2525.
The PR also try to cut down on some non idiomatic / hard to read stuff :
- expressions like `(foo (bar (buzz (qux "something"))))` , replaced by `qux "something" | buzz | bar | foo`.
- use of `coalesce` / `or` to get a default value to a possibly null or empty one (`coalesce "nullable" "defaultValue"`), replaced by `"nullable" | default "defaultValue"`
note: the boolean values in `$globals.config` that are used later in the template as a default global value to per-vhost one are currently strings rather than real booleans, and displayed as such in the debug …
> refactor: move $globals.ENV to $globals.config

- nginx.tmpl
- test/test_debug_endpoint/test_global.py
- test/test_debug_endpoint/test_global.yml
Solve bug mentioned by @SchoNie in https://github.com/nginx-proxy/nginx-proxy/pull/2525#issuecomment-2455658395
> fix: do not render regexp hostname in debug endpoint response

- test/test_logs/test_log_disabled.py
- test/test_logs/test_log_disabled.yml
Test to verify `DISABLE_ACCESS_LOGS` environment variable [disables](https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#disable-access-logs) access logs.
> test: add test for DISABLE_ACCESS_LOGS

- docs/README.md
- nginx.tmpl
- test/test_keepalive.yml
This PR [enable HTTP keepalive by default](https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#no-keepalives) with the `auto` setting.
> feat: enable keepalive by default

- docs/README.md
I think we can remove the experimental warning to clean the docs. No issues came up in #2195
> docs: remove experimental label for http loadbalance

- README.md
- docs/README.md
Use [Alerts Markdown extension](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) available since [December 2023](https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/) to better indicate the significance of the content for some documentation.
> docs: alerts markdown

- test/requirements/Dockerfile-nginx-proxy-tester
Incorporate changes from [the official install instructions](https://docs.docker.com/engine/install/debian/).
https://github.com/docker/docs/commit/33befd692249d11ce7bc88052d82709a07a8107f
Fix apt-get ascii GPG key
Changing the file extension for the GPG key to .asc lets apt-get know the GPG key is in ascii armor format, no need to dearmor.
https://github.com/docker/docs/commit/1b49c84d706d2e59b8f2300a0bdf408224ba7fc6
engine: add chmod a+r for gpg key
https://github.com/docker/docs/commit/6dc6f503e71f8f5bdce72efb50f712b5d8a371c2
engine: remove gnupg from install prerequisites
> chore: changes from upstream docker install

- nginx.tmpl
This PR refactor and clean up some parts of the template:
- `upstream_name` was set in`$globals.vhosts` two times, in the `VIRTUAL_HOST` and `VIRTUAL_HOST_MULTIPORTS` loops. It's been deduplicated to the third loop over `$globals.vhosts`.
- hard to read expressions like `when (hasKey $fooDict $bar) (get $fooDict $bar) "defaultValue"` has been replaced with the slightly clearer `get $fooDict $bar | default "defaultValue"`.
- removal / simplification of the excess logic revolving around setting the port to `legacy` for containers using `VIRTUAL_HOST`.
and fix a few things on the debug endpoint:
- addition of a terminal `\n` character to the response so that `curl | jq` on the endpoint work correctly.
- when a given path + port had more than one container, the whole `RuntimeContainer` struct …
> refactor: nginx template

- docs/README.md
- nginx.tmpl
- test/test_ssl/test_cert_selection.py
- test/test_ssl/test_cert_selection.yml
This PR closes #176 
As explained by @DonDebonair in the issue, wildcard certificate do not work the way nginx-proxy is currently trying to use them: a wildcard certificate for `*.example.com` will be valid for `foo.example.com` and `bar.example.com` but not for `sub.foo.example.com`.
> fix: wildcard certificates should only work one level deep

- .github/workflows/test.yml
- test/conftest.py
- test/requirements/Dockerfile-nginx-proxy-tester
- test/test_dockergen/test_dockergen.py
Python 3.9 will reach EOL 31 Oct 2025. But in my environment they already removed it. And the tests were failing because of `distutils.version` is deprecated since Python 3.10 and [removed](https://docs.python.org/3.12/whatsnew/3.12.html#distutils) in Python 3.12
`distutils.version` should be [replaced ](https://peps.python.org/pep-0632/#migration-advice)with the `packaging` package
This makes the test suite compatible with Python 3.12 and also 3.13. But since Python 3.13 is [not cached](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#python) in the action runner image I used Python 3.12 for now.
Changed the python module version check to 7.0.0 as that [adds official compatibility](https://docker-py.readthedocs.io/en/7.0.0/change-log.html#features). …
> ci: python 3.12+ compatibility

- README.md
- docs/README.md
The latest release version is [v1.7](https://github.com/nginx-proxy/nginx-proxy/releases/tag/1.7.0).
This PR updates the old ones in README.md.
> docs: bump docker image version

- Dockerfile.alpine
- Dockerfile.debian
- test/requirements/web/Dockerfile
Add [`syntax`](https://docs.docker.com/reference/dockerfile/#syntax) parser directive to the first line of the [Dockerfile](https://docs.docker.com/reference/dockerfile/).
To declare the Dockerfile syntax version to use for the build.
If unspecified, [BuildKit](https://docs.docker.com/build/buildkit/) uses a bundled version of the Dockerfile frontend.
Append `# syntax=docker.io/docker/dockerfile:1` to the top of the [Dockerfile](https://docs.docker.com/reference/dockerfile/).
> build: add `syntax` parser directive to Dockerfile

- test/conftest.py
- test/test_custom/test_location-per-vhost.yml
- test/test_custom/test_per-vhost.yml
- test/test_host-network-mode/test_proxy-host-network-mode.py
- test/test_htpasswd/test_htpasswd-regex-virtual-host.yml
Improvements to the DockerComposer contextmanager as mentioned in https://github.com/nginx-proxy/nginx-proxy/pull/2584#pullrequestreview-2588289338
I run the test suite as container, and found that if errors occur or on keyboardinterrupt the containers and/or networks are not cleaned properly leaving ghost stuff around and preventing new test runs.
In Github CI not a problem because after tests the runner is terminated.
- Improve the DockerComposer contextmanager to make sure teardown happens by using try except block.
- Move the self. declarations up so we are sure they are set even if an exception occurs.
- set `self._networks`
- `self._docker_compose_file = None` >>` self._docker_compose_files = None` (files typo)
- Change pytest.fail to a logging error because `pytest.fail` makes …
> tests: DockerComposer contextmanager improvements 

- docs/README.md
Users may not be aware that the filename chosen to add extra configuration in /etc/nginx/conf.d may interfere with nginx-proxy. nginx-proxy stores its configuration at /etc/nginx/conf.d/default.conf. Any files that come before default.conf in alphabetical order will be applied before default.conf and vice-versa.
This is confusing, because the documentation does not specify how exactly nginx-proxy interacts with nginx.
This can be remedied by a simple note alerting the users of the importance of filename choices.
Fixes https://github.com/nginx-proxy/nginx-proxy/issues/2593.
> docs: Add a note about configuration ordering in /etc/nginx/conf.d

- docs/README.md
Previous instructions could make the impression that user have to create a directory named as the virtual host and also a file named as the virutal host.
> Clear instruction for naming of htpasswd file

- .github/workflows/build-publish-dispatch.yml
- .github/workflows/build-publish.yml
`DOCKER_GEN_VERSION` was no longer correctly set since https://github.com/nginx-proxy/nginx-proxy/pull/2445
> fix(ci): correctly grab docker-gen version from dockerfile

- docs/README.md
- nginx.tmpl
- test/test_acme-http-challenge-location/test_acme-http-challenge-location-accept-unknown-host.py
- test/test_acme-http-challenge-location/test_acme-http-challenge-location-accept-unknown-host.yml
- test/test_acme-http-challenge-location/test_acme-http-challenge-location-disabled.py
- test/test_acme-http-challenge-location/test_acme-http-challenge-location-enabled-is-default.py
- test/test_acme-http-challenge-location/test_acme-http-challenge-location-legacy.py
Currently any ACME challenge for unknown virtual host returns 503. This is inconvenient because if the user does not use wildcard certificates, then the user must match the configuration of certificate renewal script to what virtual hosts are enabled at the time.
This must be done automatically, because due to short certificate lifetime the renewal script runs automatically. Additionally, enabling a previously disabled virtual host forces certificate renewal. Under certain circumstances this may lead to rate limiting from Let's Encrypt, because only 5 certificates for exact same set of domains can be issued per week.
Accordingly, it's worthwhile supporting unknown virtual hosts for the purposes of passing ACME challenges.
> feat: support ACME challenges for unknown virtual hosts

- nginx.tmpl
Adds missing `auth_request off;` to a few `.well-known/acme-challenge` location blocks.
This is needed to allow unrestricted access to `.well-known/acme-challenge` files on servers where `auth_request` is otherwise globally applied.
See #1409, nginx-proxy/acme-companion#570
> fix: set auth_request off for all acme challenge locations

- .github/workflows/test.yml
- test/conftest.py
- test/test_dockergen/test_dockergen.base.yml
- test/test_dockergen/test_dockergen.py
- test/test_dockergen/test_dockergen_network_segregation-custom-label.base.yml
- test/test_dockergen/test_dockergen_network_segregation-custom-label.py
- test/test_dockergen/test_dockergen_network_segregation.base.yml
- test/test_dockergen/test_dockergen_network_segregation.py
Tests introduced in #2279 where very flaky because they used the `docker_container_dns_resolver`, this PR should fix this.
I've ran the tests on this branch four times in a row without issue.
@SchoNie could you confirm ?
> test: fix docker-gen tests flakyness

- docs/README.md
- nginx.tmpl
- test/test_proxy_protocol/test_proxy-protocol-global-disabled.py
- test/test_proxy_protocol/test_proxy-protocol-global-disabled.yml
- test/test_proxy_protocol/test_proxy-protocol-global-enabled.py
- test/test_proxy_protocol/test_proxy-protocol-global-enabled.yml
Similar to #1487, I took a look at adding proxy-protocol support to this project. 
The changes included here add a new `ENABLE_PROXY_PROTOCOL` env var, which will enable proxy-protocol support for all docker-gen created listeners. Because setting `proxy_protocol` on a `listen` enables the functionality for all `server`'s that use the same port, I opted to make this option global.
Unlike the other PR, I decided to map the `x-forwarded-for` (and `x-forwarded-port`) entry to conform with current use-cases. If setting the real ip module settings is desired, there already exists methods for adding other configurations to the template.
I also added tests to verify this functionality **DOES NOT** break or modify any of the current proxy header use cases. This feature is opt-in, as nginx will …
> Proxy Protocol Support

- nginx.tmpl
Hi. This pull request adds the ability to forward the client's real IP address to the gRPC backend.
gRPC backend can get the real IP address of the client using a similar snippet:
```go
func UserIP(ctx context.Context) string {
md, ok := metadata.FromIncomingContext(ctx)
if ok {
if xRealIP := md.Get("x-real-ip"); len(xRealIP) > 0 {
return strings.Split(xRealIP[0], ",")[0]
}
}
p, ok := peer.FromContext(ctx)
if ok {
return p.Addr.String()
}
return ""
}
```
> feat: pass X-Real-IP header to gRPC Backend

- .github/workflows/build-publish-dispatch.yml
- .github/workflows/build-publish.yml
- .github/workflows/dockerhub-description.yml
- .github/workflows/test.yml
This PR add the relevant [`permissions`](https://docs.github.com/fr/actions/reference/workflows-and-actions/workflow-syntax#permissions) to the GitHub Actions workflows.
> ci: add workflows permissions

- .github/workflows/test.yml
- nginx.tmpl
- test/requirements/python-requirements.txt
- test/test_custom/my_custom_proxy_settings_baz.conf
- test/test_custom/test_defaults.py
- test/test_custom/test_defaults.yml
- test/test_custom/test_location-defaults.py
- test/test_custom/test_location-defaults.yml
- test/test_custom/test_location-per-vhost.py
- test/test_custom/test_location-per-vhost.yml
- test/test_custom/test_per-vhost.py
- test/test_custom/test_per-vhost.yml
- test/test_custom/test_proxy-wide.py
- test/test_custom/test_proxy-wide.yml
- test/test_dockergen/test_dockergen_network_segregation-custom-label.py
- test/test_dockergen/test_dockergen_network_segregation.py
Currently you can support wilcards by subdomain by using: `*.example.com`
https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#wildcard-hosts
However if you have multiple sub domains for a client next to each other like:
Main app is `*.example.com`
but api is: `*.api.example.com` and you want to use per virtual host basis configuration: https://github.com/nginx-proxy/nginx-proxy/tree/main/docs#per-virtual_host 
The current include will include the api it's configuration onto the client as well. 
This is because the include of the wildcard config domain is not escaped when the file is included for the template. This will make the file include also include the files as a regex and include the sub domain configuration files. 
By escaping the asterisk sign `*` in the file include it will …
> fix: prevent incorrect loading of wildcard domains in vhost configuration
