nginx-proxy/nginx-proxy

LICENSE

Help close: https://github.com/jwilder/nginx-proxy/issues/83
Adding a license so we can use it with other projects.

Adding license for usage

---

README.md

tested with PHP Web Application https://github.com/phundament/app

added wildcard hosts, fixes #89

---

README.md
nginx.tmpl

Support VIRTUAL_PROTO=https for HTTPS backends

---

Dockerfile

Update with the new version of docker-gen for additional features in templating.
Thanks for these awesome projects!

Updated docker-gen version to 0.3.8

---

Dockerfile

Update to nginx 1.9.2
Changelog : http://nginx.org/en/CHANGES
Thanks !

Update to nginx 1.9.2

---

Dockerfile
nginx.tmpl

Prevent generating broken config

---

nginx.tmpl

DEFAULT_HOST was not respected when using https

set default_server also for https

---

Dockerfile

As per [this](https://github.com/jwilder/docker-gen/issues/114) ticket on docker-gen. Thanks again!

Bumping to latest Docker Gen version

---

nginx.tmpl

After getting some advice over at https://github.com/nginxinc/docker-nginx/issues/39#issuecomment-137470214, I managed to fix this issue.
Fixes #216

Remove duplicate access log entries

---

README.md
nginx.tmpl

I'm still testing this, but it's mainly template fixes.  I thought I'd go ahead and make the pull request so you can look it over; if you're comfortable merging before I finish my tests then go for it, otherwise I'll let you know when I'm sure it's all working.
I also would like feedback if there is anything here you think should be done a different way.  All of these customizations are things I've found need for while using it

customizability improvements

---

nginx.tmpl

Signed-off-by: Jonas Svatos <jonas.svatos@etnetera.cz>

fix condition for default config location

---

circle.yml
test/README.md
test/default-host.bats
test/docker.bats
test/lib/README.md
test/lib/bats/batslib.bash
test/lib/bats/batslib/output.bash
test/lib/docker_helpers.bash
test/lib/helpers.bash
test/multiple-hosts.bats
test/multiple-ports.bats
test/test_helpers.bash
test/wildcard-hosts.bats

This test suite is implemented using [bats](https://github.com/sstephenson/bats).
Not all features are tested. For instance ssl features and custom nginx config are missing. Probably others. But I hope this is enough to get contributors involved in writing tests.
This test suite won't work with TravisCI. Too many evenings were wasted trying to overcome [issues](http://stackoverflow.com/questions/32846800/travis-fails-to-stop-docker-containers) that only arise on the TravisCI platform. However, it runs on [CircleCI](https://circleci.com) which is also free for opensource projects.
An example of test result from CircleCI for this test suite is available at https://circleci.com/gh/thomasleveil/nginx-proxy/45

add test suite. See #197

---

test/test_helpers.bash

This cut the test time roughly in half for me locally.

Trap TERM to allow quicker exit of web containers

---

Dockerfile
nginx.tmpl

Use trim to handle VIRTUAL_HOST values with spaces

---

.dockerignore
Makefile
README.md
circle.yml

* Update `.dockerignore` to not package up the tests
* Add a `Makefile` and instructions for running tests locally.

Testing fixups

---

README.md

Mention the issues with the v2 of the docker-compose networking as mentioned here https://github.com/jwilder/nginx-proxy/issues/304

Mention the docker-compose networking issues

---

Dockerfile

Official ddollar site has been down for a while and not sure if it's
coming back up or not.
Fixes #403

Switch forego downloads

---

.travis.yml
README.md

Add travis.yml

---

nginx.tmpl

changed error code for non-usable/default SSL cert, fixes #341

---

README.md
nginx.tmpl

This would fix #319. I successfully use this with a Flask app served by uWSGI.

connect to uWSGI backends

---

README.md
docker-compose-separate-containers.yml

Demonstrate that this pattern works.
This is based on the example at
<https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples/blob/master/docker-compose/v2/simple-site/docker-compose.yml>.

Add docker-compose file for separate containers.

---

nginx.tmpl

add ssl_session_tickets to default site

---

.travis.yml

TRAVIS: run debian and alpine tests in parallel

---

README.md

EXPOSE link in README.md resulted in a 404. Updated to a valid link.

Update EXPOSE link in README.md

---

nginx.tmpl

I want to resolve #127, adding support for IPv6

Add IPv6 listen address

---

README.md
nginx.tmpl

Fix #127 and fix #717 by improving #713

optional IPv6 support

---

test/test_events.py
test/test_events.yml

add a test to verify nginx conf is updated web a new container is created or removed

TESTS: add a test to verify nginx conf is updated

---

test/test_dockergen/test_dockergen_v3.py

Docker introduced a [new version scheme](https://blog.docker.com/2017/03/docker-enterprise-edition/). As the result, the latest docker version is now `17.03.0-ce`.
test_dockergen_v3.py is skipped in case the docker version is `< 1.13`. Version parsing needed to be adapted to the new scheme

TEST: fix #755: Tests fail with new Docker version scheme

---

nginx.tmpl

Rebased and incorporated changes from #271

Trim $host and $proto before they are used

---

Dockerfile
Dockerfile.alpine

fix worker_processes to "auto"

fix worker_processes to "auto"

---

nginx.tmpl

fix https://github.com/jwilder/nginx-proxy/issues/848

running proxy on host network

---

README.md

Remove `container_name` as not required

Simplify docker-compose.yml example

---

nginx.tmpl

Merging https://github.com/jwilder/nginx-proxy/pull/774 and https://github.com/jwilder/nginx-proxy/commit/a8ee64b0596ffc0a8df369e88d1115b80afb04fa

Do not bind upstream with 'ingress' network

---

README.md
docker-entrypoint.sh
nginx.tmpl

Previously disabled in 080a5157e6b1de3637e339a7cf54105f0316cfa7

Enable OCSP stapling if certificate trust chain is provided

---

nginx.tmpl

Grammar Police

---

nginx.tmpl

Fixes #1105.
CAUTION: This is a monkey patch.... I don't fully understand the template, but at least this patch solved my problem.

do not create an empty upstream entry for invisible containers

---

Dockerfile.alpine

This PR fixes a missing line in the alpine version.
- Fixes #1076
- See #842

Enable NETWORK_ACCESS feature for alpine version

---

nginx.tmpl
test/requirements/web/webserver.py
test/test_ssl/test_hsts.py

See nginx [doc](http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header) and [blog](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/).

Add HSTS header regardless of status code

---

Dockerfile
Dockerfile.alpine
test/test_ssl/test_dhparam.py

Similar to https://github.com/jwilder/nginx-proxy/pull/1298
Just fix the test

Upgrade nginx to 1.17

---

Dockerfile
Dockerfile.alpine

This is similar to #1298 (which use latest tag but need a rebase).

Upgrade nginx to 1.17.3

---

README.md

Fix version in README nginx banner

README.md: fix version in nginx banner

---

Dockerfile
Dockerfile.alpine
README.md

See http://nginx.org/en/CHANGES
closes #1337, resolves #1355

Upgrade to 1.17.5

---

Dockerfile
Dockerfile.alpine
README.md

😊
[https://nginx.org/en/CHANGES](https://nginx.org/en/CHANGES):
```
Changes with nginx 1.17.6                                        19 Nov 2019
*) Feature: the $proxy_protocol_server_addr and
$proxy_protocol_server_port variables.
*) Feature: the "limit_conn_dry_run" directive.
*) Feature: the $limit_req_status and $limit_conn_status variables.
```

Upgrade nginx to 1.17.6

---

Dockerfile
Dockerfile.alpine
README.md

Upgrade image to latest Nginx release. View changes [here](https://nginx.org/en/CHANGES).

Upgrade Nginx to 1.19.3

---

README.md

Just read the documentation and found this spelling issue.

Will fix spelling

---

.github/workflows/test.yml
Makefile
README.md
test/README.md
test/conftest.py
test/pytest.ini
test/requirements/Dockerfile-nginx-proxy-tester
test/requirements/README.md
test/requirements/build.sh
test/requirements/python-requirements.txt
test/requirements/web/webserver.py
test/stress_tests/test_deleted_cert/test_restart_while_missing_cert.py
test/test_custom/test_location-per-vhost.py
test/test_default-host.yml
test/test_dockergen/test_dockergen_v2.py
test/test_dockergen/test_dockergen_v3.py
test/test_events.py
test/test_ssl/test_dhparam.py
test/test_ssl/test_dhparam_generation.py
test/test_ssl/test_wildcard.py
test/test_ssl/wildcard_cert_and_nohttps/test_wildcard_cert_nohttps.py
test/test_wildcard_host.py

Migrate all CI/CD from Travis to Github Action.
All tests failed on CI because of a bug on docker-gen: https://github.com/jwilder/docker-gen/pull/335

Travis to GitHub actions

---

.github/workflows/dockerhub.yml

Self explanatory. This is mostly so we can start to field test #1607.

Build and push the dev branch to Dockerhub

---

test/conftest.py
test/requirements/python-requirements.txt

#1719 and #1722 combined so they can pass the tests.

Update docker and docker-compose pip packages

---

Dockerfile
Dockerfile.alpine
README.md
nginx.tmpl
test/test_virtual-path/alternate.conf
test/test_virtual-path/bar.conf
test/test_virtual-path/foo.conf
test/test_virtual-path/test_custom_conf.py
test/test_virtual-path/test_custom_conf.yml
test/test_virtual-path/test_virtual_paths.yml

@AlexanderLieret can I let you introduce this PR ?

Virtual path additions

---

nginx.tmpl

Remove unnecessary tabs in `nginx.tmpl`.

Remove unnecessary tabs

---

Dockerfile
Dockerfile.alpine

Bump docker-gen from 0.8.2 to 0.8.4

---

README.md

`DEFAUL_ROOT` should be `DEFAULT_ROOT`

Simple mistake in DEFAULT_ROOT variable name

---

Dockerfile
Dockerfile.alpine

build: dockergen 0.9.1 -> 0.9.2

---

Dockerfile
Dockerfile.alpine

Patch version bump, dependencies update on docker-gen side.

build: dockergen 0.9.3 -> 0.9.4

---

nginx.tmpl
test/test_vhost-empty-string.py
test/test_vhost-empty-string.yml

Fixes #2144
@thomasmerz Would you please test this to see if it fixes your issue?

fix: Ignore `VIRTUAL_HOST` set to the empty string

---

nginx.tmpl
test/test_log_format.py
test/test_log_format.yml

Related to https://github.com/nginx-proxy/nginx-proxy/discussions/2133

Support LOG_FORMAT env variable.

---

README.md

Documentation for https://github.com/nginx-proxy/nginx-proxy/pull/2151

Documentation custom log format.

---

nginx.tmpl

This will make planned future changes easier.

chore: Factor out container IP:port lookup

---

Dockerfile
Dockerfile.alpine

build: dockergen 0.9.4 -> 0.10.0

---

Dockerfile
Dockerfile.alpine

Version bump, will fix "incorrect value" log issues.

build: dockergen 0.10.0 -> 0.10.1

---

Dockerfile
Dockerfile.alpine

build: docker-gen 0.10.2 -> 0.10.3

---

test/stress_tests/test_deleted_cert/test_restart_while_missing_cert.py

@SchoNie unfortunately it seems that the tests 
- `test_delete_cert_and_restart_reverseproxy`
- `test_unknown_virtual_host_is_still_503`
- `test_http_web_is_now_200`
are still flaky:
- [first run where the debian version fails](https://github.com/nginx-proxy/nginx-proxy/actions/runs/7311066594/attempts/1)
- [second run where the alpine version fails](https://github.com/nginx-proxy/nginx-proxy/actions/runs/7311066594/attempts/2)
- [etc...](https://github.com/nginx-proxy/nginx-proxy/actions/runs/7311066594)

test: revert "Fix test" and "Sleep longer"

---

.github/workflows/build-publish.yml

Add s390x support

---

docs/README.md
nginx.tmpl

Redo of #2300 without the merge conflict (can't push to @jmformenti branch so can't fix the conflict on the opened PR).

feat: define basic auth for virtual path

---

docs/README.md

fix typo README.md

---

test/test_htpasswd/htpasswd/htpasswd.nginx-proxy.tld
test/test_htpasswd/htpasswd/htpasswd.nginx-proxy.tld_8d960560c82f4e6c8b1b0f03eb30a1afd00e5696
test/test_htpasswd/test_htpasswd_virtual_host.py
test/test_htpasswd/test_htpasswd_virtual_host.yml
test/test_htpasswd/test_htpasswd_virtual_path.py
test/test_htpasswd/test_htpasswd_virtual_path.yml

Tests for `VIRTUAL_HOST` and `VIRTUAL_PATH` htpasswd behaviour
Draft until #2401 is merged (assertion on path without double slash)

tests: htpasswd

---

docs/README.md

Some QoL improvements on the docs with reordering, better grouping and a table of contents.

docs: redordering, grouping and navigation

---

test/conftest.py
test/test_ssl/acme_root/.well-known/acme-challenge/test-filename
test/test_ssl/test_https_port.py
test/test_ssl/test_https_port.yml
test/test_ssl/test_nohttp.py
test/test_ssl/test_nohttp.yml
test/test_ssl/test_nohttps.py
test/test_ssl/test_nohttps.yml
test/test_ssl/test_noredirect.py
test/test_ssl/test_noredirect.yml
test/test_ssl/test_virtual_path.py
test/test_ssl/test_virtual_path.yml
test/test_ssl/test_wildcard.py
test/test_ssl/test_wildcard.yml
test/test_ssl/wildcard_cert_and_nohttps/acme_root/.well-known/acme-challenge/test-filename
test/test_ssl/wildcard_cert_and_nohttps/docker-compose.yml
test/test_ssl/wildcard_cert_and_nohttps/test_wildcard_cert_nohttps.py

At the moment no changes to functionality are done, only the current behavior is captured.
In the future I will suggest improvements in this area.

tests: Add tests for how Let's Encrypt ACME challenge is handled

---

Dockerfile.alpine
Dockerfile.debian

to build with podman / buildah.

build: disambiguate base image names

---

docs/README.md
test/test_acme_http_challenge_location/test_acme_challenge_location_disabled.py
test/test_acme_http_challenge_location/test_acme_challenge_location_enabled.py
test/test_acme_http_challenge_location/test_acme_challenge_location_legacy_is_default.py

chore: spelling fixes for #2468

---

README.md
docs/README.md

Updated to 1.6 in root README.md
Removed version in docs/README.md to equalize with other examples in that file.

docs: update version in README.md

---

docs/README.md

This PR add a new doc section that attempt to summarize all the available configuration options.

docs: config summary

---

docker-compose-separate-containers.yml

Added precision for 3-container version

docs: add precisions to multi container compose file
